name: Firebase Deploy Stg[firestore:indexes]
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/firestore_indexes_stg.yml
      - firestore.indexes.json

jobs:
  deploy:
    name: Deploy for Firestore Indexes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        run: |
          yarn add -D firebase-tools
          ./node_modules/.bin/firebase deploy --only firestore:indexes --token=${{ secrets.FIREBASE_TOKEN }} --project ${{ secrets.STG_PROJECT_ID }}
