  
name: Firebase Build and Deploy[functions]
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/functions.yml
      - 'functions/**'

jobs:
  build:
    name: Build For Functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
        run: |
          cd functions
          yarn
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
        run: |
          cd functions
          yarn build
      - name: Archive Production Artifact[lib]
        uses: actions/upload-artifact@master
        with:
          name: functions-lib
          path: functions/lib
      - name: Archive Production Artifact[node_modules]
        uses: actions/upload-artifact@master
        with:
          name: functions-node_modules
          path: functions/node_modules
  deploy:
    name: Deploy for Functions
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact[lib]
        uses: actions/download-artifact@master
        with:
          name: functions-lib
          path: functions/lib
      - name: Download Artifact[node_modules]
        uses: actions/download-artifact@master
        with:
          name: functions-node_modules
          path: functions/node_modules
      - name: Deploy to Firebase
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
        run: |
          yarn add -D firebase-tools
          ./node_modules/.bin/firebase deploy --only functions --token=${{ secrets.FIREBASE_TOKEN }} --non-interactive -f
