name: Firebase Build and Deploy[hosting:nomoca-lp]
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/hosting_lp.yml
      - 'lp/**'

jobs:
  build:
    name: Build For Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd lp
          yarn
      - name: Build
        run: |
          cd lp
          yarn build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: lp-dist
          path: lp/dist
  deploy:
    name: Deploy for Hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: lp-dist
          path: lp/dist
      - name: Deploy to Firebase
        run: |
          yarn add -D firebase-tools
          ./node_modules/.bin/firebase deploy --only hosting:nomoca-lp --token=${{ secrets.FIREBASE_TOKEN }}
