  
name: Firebase Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build For Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd admin
          yarn
      - name: Build
        run: |
          cd admin
          yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: admin-dist
          path: admin/dist
  deploy:
    name: Deploy for Hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: admin-dist
          path: admin/dist
      - name: Deploy to Firebase
        run: |
          yarn add -D firebase-tools
          ./node_modules/.bin/firebase deploy --only hosting:admin --token=${{ secrets.FIREBASE_TOKEN }}
