name: Firebase Deploy[storage:rules]
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/storage_rules.yml
      - storage.rules

jobs:
  deploy:
    name: Deploy for Storage Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        run: |
          yarn add -D firebase-tools
          ./node_modules/.bin/firebase deploy --only storage:rules --token=${{ secrets.FIREBASE_TOKEN }}
